# Generated by Django 4.2.10 on 2024-02-16 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_friends_user_friends_count_user_posts_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collab_suggestions',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
