# Generated by Django 4.2.10 on 2024-02-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_trend_posts_comments_count_posts_likes_count_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
